language: ruby
os:
  - linux
  - osx
before_install:
  - gem install -v 1.16.0 bundler
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4.2
  - 2.5.3
  - 2.6.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
  - os: osx
    rvm: 2.0.0